-- Création utilisateur
CREATE USER TP_DICT IDENTIFIED BY tp_dict
DEFAULT TABLESPACE USERS
QUOTA UNLIMITED ON USERS;

GRANT CONNECT, RESOURCE TO TP_DICT;

-- Connexion
CONNECT TP_DICT/tp_dict;

-- Table CLIENTS
CREATE TABLE CLIENTS (
    id_client NUMBER PRIMARY KEY,
    nom VARCHAR2(50),
    ville VARCHAR2(50)
);

-- Table COMMANDES
CREATE TABLE COMMANDES (
    id_commande NUMBER PRIMARY KEY,
    montant NUMBER,
    id_client NUMBER,
    CONSTRAINT fk_client FOREIGN KEY (id_client) REFERENCES CLIENTS(id_client)
);

-- Index
CREATE INDEX idx_clients_nom ON CLIENTS(nom);

-- Vue SQL
CREATE VIEW VUE_CLIENTS_PARIS AS
SELECT * FROM CLIENTS WHERE ville = 'Paris';

-- Séquence
CREATE SEQUENCE seq_commande START WITH 1;

-- Données
INSERT INTO CLIENTS VALUES (1,'Dupont','Paris');
INSERT INTO CLIENTS VALUES (2,'Martin','Lyon');
INSERT INTO CLIENTS VALUES (3,'Durand','Paris');

INSERT INTO COMMANDES VALUES (1,100,1);
INSERT INTO COMMANDES VALUES (2,200,2);
INSERT INTO COMMANDES VALUES (3,150,1);

COMMIT;

