# Configuration par defaut

oracle.host=localhost
oracle.port=1521
oracle.service=ORCLPDB1

# Configuration du user system

system.db.username=system
system.db.password=Oracle123
system.db.host=localhost
system.db.port=1521
system.db.oracle.service=ORCLPDB1


# Configuration du user gaza

gaza.db.username=gaza
gaza.db.password=gaza123
gaza.db.host=localhost
gaza.db.port=1521
gaza.db.oracle.service=ORCLPDB1


# Configuration du user mata

mata.db.username=mata
mata.db.password=mata123
mata.db.host=localhost
mata.db.port=1521
mata.db.oracle.service=ORCLPDB1
