# Configuration par defaut

oracle.host=localhost
oracle.port=1521
oracle.service=ORCLPDB1

# Configuration du user system

system.db.username=system
system.db.password=Oracle123
gaza.db.host=localhost
gaza.db.port=1521
gaza.db.oracle.service=ORCLPDB1


# Configuration du user gaza

gaza.db.username=gaza
gaza.db.password=gaza123
gaza.db.host=localhost
gaza.db.port=1521
gaza.db.oracle.service=ORCLPDB1

